### ISSUE TITLE
Silently fails at or near antipodal cases at equator

### ISSUE THREAD

**Issue by mxfh** [vivescere/uvincenty#1]
For longitudinal distances on equator with difference >= 179.397 degrees -1 is returned
Where distance via poles should be shorter.

e.g. coord pairs like 
```
uvincenty.vincenty(0, 0, 0, 179.397)
uvincenty.vincenty(0, 0, 0, 180) 
```
return -1

**Comment by vivescere** [comment]
Hi! This indicates a failure to converge. The original vincenty package returns None, would that be better?

https://en.wikipedia.org/wiki/Vincenty%27s_formulae#Nearly_antipodal_points

**Comment by mxfh** [comment]
None is better, since -1 is a valid distance for signed movements on geodesics.

using geopy for now, which had the issue before, and solved it by using geographiclib. 

https://github.com/geopy/geopy/issues/30
the python one, or the C version

https://geographiclib.sourceforge.io/html/python/code.html#module-geographiclib.geodesic
using geographiclib directly is probably the best option in a reference application for my usecase

for reference also see: Algorithms for geodesics by same author, Charles F. F. Karney 
https://arxiv.org/pdf/1109.4448.pdf

**Comment by vivescere** [comment]
Changed it to return None instead (da7d18ece667fa51afec989be04ac5e688b1dbf6). Updated the PyPI repo, should be installable now (probably using --no-cache-dir when using pip).

Should have thought of that kind of use (and not used -1), thank you for the precision!
